<a href="https://colab.research.google.com/github/Akhilesh1118/Data-Science_NF/blob/main/Module%202/Homework/Join.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
# Merging & Joining
info = pd.DataFrame({
"name": ["Saurav", "Kuldeep", "Akash", "Gaurav"],
"roll_no": [101, 102, 103, 104],
})
marks = pd.DataFrame({
"marks": [92, 90, 85, 96],
"roll_no": [101, 102, 103, 104],
"Dept": ["CSE", "CSE", "CDS", "CSE"]

})

In [3]:

pd.merge(info, marks, on="roll_no")    # Inner Join

      name  roll_no  marks Dept
0   Saurav      101     92  CSE
1  Kuldeep      102     90  CSE
2    Akash      103     85  CDS
3   Gaurav      104     96  CSE

In [4]:
pd.merge(info, marks, on="roll_no", how="left")   # Left Join

      name  roll_no  marks Dept
0   Saurav      101     92  CSE
1  Kuldeep      102     90  CSE
2    Akash      103     85  CDS
3   Gaurav      104     96  CSE

In [5]:
pd.merge(info, marks, on="roll_no", how="right")  # Right Join

      name  roll_no  marks Dept
0   Saurav      101     92  CSE
1  Kuldeep      102     90  CSE
2    Akash      103     85  CDS
3   Gaurav      104     96  CSE

In [6]:
pd.merge(info, marks, on="roll_no", how="outer") # Outer Join

      name  roll_no  marks Dept
0   Saurav      101     92  CSE
1  Kuldeep      102     90  CSE
2    Akash      103     85  CDS
3   Gaurav      104     96  CSE