<a href="https://colab.research.google.com/github/Akhilesh1118/Data-Science_NF/blob/main/Module%202/Classwork/Ch2_2_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Joining DataFrames
What is join() in Pandas ?
- join() is used to combiine two DataFrames based on their index
- It is simpler than merge () when data is already indexed
- Mainly used when :
> One Data frame is primary \
> Aother DataFrame adds extra columns

In [ ]:
import pandas as pd

Df1 = pd.DataFrame({"A": [1, 2, 3, 4], "B": ["A", "B", "C", "D"]})

Df2 = pd.DataFrame({ "C": [1, 2, 3, 4], "D": ["a", "b", "c", "d"]})

In [ ]:
Df1 = pd.DataFrame({"A": [1, 2, 3, 4], "B": ["A", "B", "C", "D"]})

Df2 = pd.DataFrame({ "C": [1, 2, 3, 4], "D": ["a", "b", "c", "d"]})

Index in join .

In [ ]:
Df1 = pd.DataFrame({"A": [1, 2, 3, 4], "B": ["A", "B", "C", "D"]}, index=["a" , "b" , 2, "d"])

Df2 = pd.DataFrame({ "C": [1, 2, 3, 4], "D": ["a", "b", "c", "d"]})
Df1.join(Df2)

   A  B    C    D
a  1  A  NaN  NaN
b  2  B  NaN  NaN
2  3  C  3.0    c
d  4  D  NaN  NaN

In [ ]:
Df1 = pd.DataFrame({"A": [1, 2, 3, 4], "B": ["A", "B", "C", "D"]}, index=["a" , "b" , 2, "d"])

Df2 = pd.DataFrame({ "C": [1, 2, 3, 4], "D": ["a", "b", "c", "d"]}, index=["a",2,"d" , "b"])
Df1.join(Df2)

   A  B  C  D
a  1  A  1  a
b  2  B  4  d
2  3  C  2  b
d  4  D  3  c

In [ ]:
Df1 = pd.DataFrame({"A": [1, 2, 3, 4], "B": ["A", "B", "C", "D"]}, index=["a" , "b" , 2, "d"])

Df2 = pd.DataFrame({ "C": [1, 2], "D": ["a", "b"]}, index=["c" , "d" ])

Df1.join(Df2,how="inner")

   A  B  C  D
d  4  D  2  b

In [ ]:
Df1 = pd.DataFrame({"A": [1, 2, 3, 4], "B": ["A", "B", "C", "D"]}, index=["a" , "b" , 2, "d"])

Df2 = pd.DataFrame({ "C": [1, 2], "D": ["a", "b"]}, index=["c" , "d" ])

Df1.join(Df2,how="outer")

     A    B    C    D
2  3.0    C  NaN  NaN
a  1.0    A  NaN  NaN
b  2.0    B  NaN  NaN
c  NaN  NaN  1.0    a
d  4.0    D  2.0    b

In [ ]:
Df1 = pd.DataFrame({"A": [1, 2, 3, 4], "B": ["A", "B", "C", "D"]}, index=["a" , "b" , 2, "d"])

Df2 = pd.DataFrame({ "C": [1, 2], "D": ["a", "b"]}, index=["c" , "d" ])

Df1.join(Df2,how="left")

   A  B    C    D
a  1  A  NaN  NaN
b  2  B  NaN  NaN
2  3  C  NaN  NaN
d  4  D  2.0    b

In [ ]:
Df1 = pd.DataFrame({"A": [1, 2, 3, 4], "B": ["A", "B", "C", "D"]}, index=["a" , "b" , 2, "d"])

Df2 = pd.DataFrame({ "C": [1, 2], "D": ["a", "b"]}, index=["c" , "d" ])

Df1.join(Df2,how="right" )

     A    B  C  D
c  NaN  NaN  1  a
d  4.0    D  2  b