<a href="https://colab.research.google.com/github/Akhilesh1118/Data-Science_NF/blob/main/Module%202/Classwork/Chapter_1.1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# PANDAS SERIES
import pandas as pd
l1=[2,4,6,8,10]
var=pd.Series(l1)
print(var)
print(type(var))

0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>

In [ ]:
l1=[2,4,6,8,10]
var=pd.Series(l1,index=["a","bYE","3","d","akhilesh"])     # CUSTOMIZED INDEX
print(var)

a         2
bYE       4
3         6
d         8
ankur    10
dtype: int64

In [ ]:
l1=[2,4,6,8,10]
var=pd.Series(l1,index=["a","bYE","3","d","akhilesh"],dtype="float")     # CUSTOMIZED value type from integer to float
print(var)

a         2.0
bYE       4.0
3         6.0
d         8.0
ankur    10.0
dtype: float64

In [ ]:

l1=[2,4,6,8,10]
var=pd.Series(l1,index=["a","bYE","3","d","akhilesh"],dtype="float", name="akhilesh") # adding name
print(var)

a         2.0
bYE       4.0
3         6.0
d         8.0
ankur    10.0
Name: ankur, dtype: float64

In [ ]:
var2=pd.Series(5, index=[1,2,3,4,5])     # it's like (5) * [1,2,3,4,5]= [5,5,5,5,5] at [1,2,3,4,5]
print(var2)

1    5
2    5
3    5
4    5
5    5
dtype: int64

In [ ]:
var2=pd.Series(5)
print(var2)

0    5
dtype: int64

In [ ]:
var2=pd.Series(5, index=[2,7,9,13,1])
var3=pd.Series(10, index=[1,5,9,11,13])
print(var2+var3)

1     15.0
2      NaN
5      NaN
7      NaN
9     15.0
11     NaN
13    15.0
dtype: float64

In [ ]:
d1={
    "name":["akhilesh","aditya"],
    "roll":[14,11 ],
    "age":[21,21]
}
var4=pd.Series(d1)
print(var4)

name    [ankur, aditya]
roll           [14, 11]
age            [21, 21]
dtype: object

In [ ]:
# series operations
myseries=[2,3,4,5,6]
v=pd.Series(myseries)
sum=v.sum()
max=v.max()
min=v.min()
print(sum)
print(max)
print(min)
print(v)

20
6
2
0    2
1    3
2    4
3    5
4    6
dtype: int64

In [ ]:
import pandas as pd
l1=[2,4,6,8,10]
df= pd.DataFrame(l1)
print(df)
print(type(df))

    0
0   2
1   4
2   6
3   8
4  10
<class 'pandas.core.frame.DataFrame'>

In [ ]:
info={
    "name":"akhilesh",
    "age":21,
    "marks":99.5,
    "status": True
}

df=pd.DataFrame(info,index=["A","B","C"])
print(df)
print(type(df))

    name  age  marks  status
A  ankur   21   99.5    True
B  ankur   21   99.5    True
C  ankur   21   99.5    True
<class 'pandas.core.frame.DataFrame'>

In [ ]:
info={
    "name":["akhilesh","aditya","aditya"],
    "age":[21,22,23],
    "marks":[99.5,99.8,99.7],
    "status": True
}

df=pd.DataFrame(info)
print(df)

     name  age  marks  status
0   ankur   21   99.5    True
1  aditya   22   99.8    True
2  aditya   23   99.7    True

In [ ]:
info={
    "name":["akhilesh","aditya","aditya"],
    "age":[21,22,23],
    "marks":[99.5,99.8,99.7],
    "status": True
}

df=pd.DataFrame(info, columns=["name", "marks"])
print(df)

     name  marks
0   ankur   99.5
1  aditya   99.8
2  aditya   99.7

In [ ]:
info={
    "name":["akhilesh","aditya","aditya"],
    "age":[21,22,23],
    "marks":[99.5,99.8,99.7],
    "status": True
}

df=pd.DataFrame(info, columns=["name", "marks"])
print(df["name"][2])

aditya

In [ ]:
l2= [["a","b","c","d"],["A","B","C","D"]]
df=pd.DataFrame(l2)
print(df)

   0  1  2  3
0  a  b  c  d
1  A  B  C  D

In [ ]:
SR={
    "S" : pd.Series([1,2,3,4]),
    "R" : pd.Series(["a","b","c","d"])
}
df=pd.DataFrame(SR)
df

   S  R
0  1  a
1  2  b
2  3  c
3  4  d

In [ ]:
df=pd.DataFrame({"A":[2,4,6,8],"B": [3,5,7,9]})
df["e"]=df["A"]+df["B"]
df

   A  B   e
0  2  3   5
1  4  5   9
2  6  7  13
3  8  9  17

In [ ]:
df=pd.DataFrame({"A":[2,4,6,8],"B": [3,5,7,9]})
df["e"]=df["A"]+df["B"]
df["try"]=df["A"]>4
df["try"]=df["A"]<5
df

   A  B   e    try
0  2  3   5   True
1  4  5   9   True
2  6  7  13  False
3  8  9  17  False

In [ ]:
# 01 june notes ::

# 1. dataset upload
# 2. dataset view {}
# 3. misssing values levels
# 4. duplicate
# 5. standralize column
# 6. data type check
# 7. text clean
# 8. category
# 9. transformation add/remove
# 10. make it/ save it as a csv file


# Merging and Joining ::

# merge and joins are used to :
# 1. combine related dataset
# 2. perform database-style operations
# 3. analyze data from multiple sources
# 4. clean and organise large datasets


# ways to combine dataframs in pandas ::

# pandas provide three main methods :
# 1. merge() : column- based joins
# 2. join() : index - based joins
# 3. concat() : stacking dataframes

# merge() function : the merge() function is used for SQL-style joins .
# syntax : pd.merge( df1,df2, on= "column_name", how= "inner")


# types of joins in merge :
# 1. inner
# 2. outer
# 3. left
# 4. right